USE [IFF]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[view_autoridades]
AS
SELECT     TOP (100) PERCENT a.CODIGO AS ID_AUTORIDADE, a.TIPO, aus.VALOR AS NOME
FROM         biblioteca.AUTORIDADES AS a INNER JOIN
                      biblioteca.AUTORIDADE_TAG AS at ON at.IDFK_AUTORIDADES = a.CODIGO INNER JOIN
                      biblioteca.AUTORIDADE_SUBCAMPO AS aus ON aus.IDFK_AUTORIDADE_TAG_DADO = at.ID_AUTORIDADE_TAG
WHERE     (at.TAG IN (110, 100, 130)) AND (aus.SUBCAMPO = 'a')
ORDER BY ID_AUTORIDADE

GO