USE [IFF]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[view_assuntos]
AS
	SELECT     TOP (100) PERCENT ID_REGISTRO_SUBCAMPO AS ID_ASSUNTO, ID_REGISTRO AS IDFK_REGISTRO, VALOR AS ASSUNTO
	FROM         dbo.view_tags_subcampos AS vts
	WHERE     (TAG = 650) AND (SUBCAMPO = 'a')
	ORDER BY IDFK_REGISTRO
GO